### ISSUE TITLE
About peak memory in scripts example?

### ISSUE THREAD

**Issue by laihongphuc** [wuyushuwys/FMEDiffusion#2]
Hello authors, thank for your interesting work!
I run the examples provided in scipts folder on a V100 GPU (32GB VRAM). The peak memory of FME pipeline is about 28.54GB and the peak memory of original SVD is 30.51GB, and the latency of original SVD is also better. Are there something i'm missing, because the result is not good as in paper Tab. 1. 
Thanks a lot!

**Comment by wuyushuwys** [comment]
Hello @laihongphuc, could you please provide you testing scripts? We tested on A100 and A6000, and both are similar as mentioned in  [note](https://github.com/wuyushuwys/FMEDiffusion?tab=readme-ov-file#the-peak-memory-values-may-not-exactly-match-those-reported-in-the-paper).

**Comment by laihongphuc** [comment]
I use the code in [example](https://github.com/wuyushuwys/FMEDiffusion/tree/main/scripts). The peak memory of original SVD is 30.51GB, can run on 32GB gpu

**Comment by wuyushuwys** [comment]
Thanks, we will take a look for this issue later on V100-32G.

Also, may we have the diffusers version you used?

**Comment by laihongphuc** [comment]
I use `diffusers` version 0.30.3

**Comment by wuyushuwys** [comment]
Hello @laihongphuc , we've tested our code on Tesla V100-SXM2-32GB and the result looks good as below. 
![results_v100](https://github.com/user-attachments/assets/5592abdb-9740-408f-96ea-dde69335ee25)

Can you please confirm you don't have other tasks that occupy the GPU memory at the same time? Since i noticed the `model load memory` is 14.53G, which should be around 5G in our test.
Our memory benchmark tool is based on `pynvml`, which has the similar output as in `nvidia-smi`. 

We will push a new update of the repo. Thanks.

**Comment by laihongphuc** [comment]
Hello @wuyushuwys, I've tested your code again on V100 and the result is matched with your result. However the gap about memory peak with your pipeline and original pipeline isn't so good. 
![image](https://github.com/user-attachments/assets/8a49d01a-cfe4-42b2-bfda-0e1ffdf24a6c)
Do the current codes support Operator Grouping and Feature Rehashing in paper? 
Thank you!

**Comment by wuyushuwys** [comment]
Hello @laihongphuc, We are aware of the issue you have. We believe it might related to some offload mechanism, since if you trace the realtime memory usage, you will find the memory usage exceeding the _output_ value at some point.
Thanks for pointing out this issue. We plan to release a new example code for tracing peak memory.

**Comment by wuyushuwys** [comment]
Hello @laihongphuc, if you trace the memory snapshot according to [link](https://pytorch.org/docs/stable/torch_cuda_memory.html), you can catch this as well on V100 GPU.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/bc32acf4-f756-4e29-8a03-0220110285a4">
